---
- name: Configure Web Servers
  hosts: webservers
  gather_facts: no
  tasks:
    - name: Display server info
      debug:
        msg: 'Configuring web server: {{ inventory_hostname }}'
    
    - name: Create app directory
      file:
        path: /tmp/feedback-app
        state: directory
        mode: '0755'
    
    - name: Create config file
      shell: echo 'Web server {{ inventory_hostname }} configured' > /tmp/feedback-app/{{ inventory_hostname }}.log
      
- name: Configure Database Servers
  hosts: dbservers
  gather_facts: no
  tasks:
    - name: Display db server info
      debug:
        msg: 'Configuring database server: {{ inventory_hostname }}'
    
    - name: Create db directory
      file:
        path: /tmp/feedback-db
        state: directory
        mode: '0755'
    
    - name: Create db config
      shell: echo 'Database server {{ inventory_hostname }} configured' > /tmp/feedback-db/{{ inventory_hostname }}.log